import os
from typing import List, Dict, Any, Optional
from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel, Field
from engine.ingestion import TXTIngestor
from engine.query import RAGQueryPipeline


app = FastAPI(
    title="RAG Service API",
    description="API for ingesting text files into ChromaDB and querying the RAG pipeline.",
    version="1.0.0"
)

DATA_DIR = "./data"
ingestor = TXTIngestor(db_dir="./chroma_db", collection_name="rag_collection")
rag_pipeline = RAGQueryPipeline(config_path="engine/adapters/adapter_config.json", db_dir="./chroma_db")


# -------------------------------------------------------------------
# PYDANTIC MODELS (Request / Response Validation)
# -------------------------------------------------------------------

class IngestionResponse(BaseModel):
    status: str = Field(..., example="success")
    message: str = Field(..., example="Successfully ingested files from data folder.")
    processed_files: List[str] = Field(default_factory=list, example=["document1.txt", "notes.txt"])
    skipped_files: List[str] = Field(default_factory=list, example=["image.png"])


class QueryRequest(BaseModel):
    query: str = Field(..., min_length=1, description="The natural language question for the RAG system.", example="What is RAG?")
    top_k: Optional[int] = Field(default=3, ge=1, le=10, description="Number of document chunks to retrieve.")


class DocumentChunk(BaseModel):
    id: str
    content: str
    metadata: Dict[str, Any]
    distance: float


class QueryResponse(BaseModel):
    query: str
    answer: str
    retrieved_docs: List[DocumentChunk]



@app.get("/ingest", response_model=IngestionResponse, summary="Ingest TXT files from data folder")
def ingest_data_folder():
    """
    Reads all `.txt` files inside the `./data` directory, chunks them, 
    generates embeddings via OllamaAdapter, and ingests unique chunks into ChromaDB.
    """
    if not os.path.exists(DATA_DIR):
        raise HTTPException(
            status_code=404, 
            detail=f"Directory '{DATA_DIR}' does not exist. Please create it and add .txt files."
        )

    processed_files = []
    skipped_files = []

    try:
        files = os.listdir(DATA_DIR)
        txt_files = [f for f in files if f.endswith(".txt")]

        if not txt_files:
            return IngestionResponse(
                status="success",
                message="No .txt files found in data folder to process.",
                processed_files=[],
                skipped_files=[f for f in files if not f.endswith(".txt")]
            )

        for file_name in txt_files:
            file_path = os.path.join(DATA_DIR, file_name)
            ingestor.ingest_file(file_path, chunk_size=1000, chunk_overlap=100)
            processed_files.append(file_name)

        skipped_files = [f for f in files if not f.endswith(".txt")]

        return IngestionResponse(
            status="success",
            message=f"Successfully processed {len(processed_files)} file(s).",
            processed_files=processed_files,
            skipped_files=skipped_files
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ingestion failed: {str(e)}")


@app.post("/query", response_model=QueryResponse, summary="Query RAG pipeline")
def query_rag(request: QueryRequest):
    """
    Accepts a user query, retrieves relevant document context from ChromaDB,
    and returns an answer generated by Ollama.
    """
    try:
        result = rag_pipeline.run(query=request.query, top_k=request.top_k)

        # Map raw dictionary results to Pydantic DocumentChunk objects
        formatted_docs = [
            DocumentChunk(
                id=doc["id"],
                content=doc["content"],
                metadata=doc["metadata"],
                distance=doc["distance"]
            )
            for doc in result["retrieved_docs"]
        ]

        return QueryResponse(
            query=request.query,
            answer=result["answer"],
            retrieved_docs=formatted_docs
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Query execution failed: {str(e)}")


# Endpoint for basic health check
@app.get("/health")
def health_check():
    return {"status": "healthy"}